# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.49973173 0.22231396 0.85633486]
  [0.30300764 0.50595852 0.55891909]
  [0.65196861 0.14712084 0.58312339]]

 [[0.07553082 0.54535965 0.15671947]
  [0.48939018 0.97712101 0.54577106]
  [0.28086596 0.82152232 0.84772647]]

 [[0.6455765  0.07241092 0.58845578]
  [0.31804317 0.93455737 0.5661044 ]
  [0.08179405 0.72567495 0.97485551]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
import numpy as np
x = np.diag([1, 2, 3, 4,0])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.21327283 0.72160901 0.69168835 0.19222815 0.10299467]
 [0.53487668 0.62781515 0.12544087 0.23889666 0.23119391]
 [0.11448006 0.23384086 0.88499852 0.75224518 0.60310445]
 [0.98311077 0.60396913 0.55562066 0.96900059 0.99088967]
 [0.64929393 0.72291536 0.71843058 0.8090534  0.94615062]]
After normalization:
[[0.1242018  0.69672016 0.66302173 0.10050004 0.        ]
 [0.48641114 0.59108395 0.02528024 0.15306088 0.14438559]
 [0.01293552 0.14736673 0.88073912 0.73122443 0.56325329]
 [0.99123894 0.56422714 0.50977423 0.97534722 1.        ]
 [0.61527462 0.69819144 0.69314042 0.79520521 0.94961223]]


# 5.  How to find common values between two arrays?

In [8]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [10]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[0 1 1 0 0 0]
Second array:
[0 1 1 1 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)



Original array:
[0.08949961 0.01682018 0.50885897 0.50255539 0.99684887 0.10971387
 0.87013074 0.28320604 0.31647274 0.08546346]
Maximum value replaced by 0:
[0.08949961 0.01682018 0.50885897 0.50255539 0.         0.10971387
 0.87013074 0.28320604 0.31647274 0.08546346]


# 9. How to print all the values of an array?

In [15]:
import numpy as np
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [16]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.54295557 0.13153591 0.23390411 0.00958569 0.53929815 0.62877163
  0.54883555 0.41872162 0.07681254 0.68087555]
 [0.84208991 0.16692321 0.78499493 0.31265091 0.29315103 0.16848097
  0.57219855 0.98142312 0.5718159  0.07773262]
 [0.43655145 0.50781386 0.06785177 0.36930473 0.93337105 0.68803591
  0.73949353 0.09395631 0.46133462 0.74355527]
 [0.11657833 0.21432511 0.56003283 0.03933518 0.35733506 0.70870212
  0.56415545 0.86129518 0.51781006 0.54834135]
 [0.21192234 0.59520101 0.58201544 0.06636677 0.42042262 0.47783416
  0.34809694 0.90483079 0.44223041 0.73868007]]

Subtract the mean of each row of the said matrix:

[[ 0.16182594 -0.24959373 -0.14722552 -0.37154394  0.15816852  0.247642
   0.16770592  0.03759199 -0.30431709  0.29974592]
 [ 0.3649438  -0.31022291  0.30784881 -0.1644952  -0.18399508 -0.30866514
   0.09505243  0.504277    0.09466978 -0.39941349]
 [-0.0675754   0.00368701 -0.43627508 -0.13482212  0.4292442   0.18390906
   0.23536668 -0.41017054 -0.042

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [17]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 4. 2. 2. 2. 3. 5. 1. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [18]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))


np.diag(np.dot(A, B))


np.sum(A * B.T, axis=1)


np.einsum("ij,ji->i", A, B)

array([ 48,  23, 108])

# 13.How to find the most frequent value in an array?

In [19]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[6 6 1 5 2 8 2 2 9 4 6 3 4 1 2 8 0 9 1 8 0 7 7 7 8 6 3 2 3 6 0 6 6 9 9 4 6
 1 6 5 3 6 9 5 7 3 6 6 9 2]
rank: 6


# 14.How to get the n largest values of an array

In [20]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9997 9999 9995]


# 15.How to create a record array from a regular array?

In [22]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')